// <auto-generated />
namespace F2022A6DS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class richerdatapropertiesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(richerdatapropertiesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202212032344309_richer-data-properties-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
